"""add_ledger_and_card_limits

Revision ID: cdd5a04f9914
Revises: e3d851ea9d54
Create Date: 2026-06-19 14:02:08.973634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd5a04f9914'
down_revision: Union[str, Sequence[str], None] = 'e3d851ea9d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_account_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_account_id'], ['virtual_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['virtual_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_transactions_destination_account_id'), 'virtual_transactions', ['destination_account_id'], unique=False)
    op.create_index(op.f('ix_virtual_transactions_source_account_id'), 'virtual_transactions', ['source_account_id'], unique=False)
    op.add_column('virtual_cards', sa.Column('daily_limit_paise', sa.Integer(), nullable=True))
    op.add_column('virtual_cards', sa.Column('monthly_limit_paise', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_cards', 'monthly_limit_paise')
    op.drop_column('virtual_cards', 'daily_limit_paise')
    op.drop_index(op.f('ix_virtual_transactions_source_account_id'), table_name='virtual_transactions')
    op.drop_index(op.f('ix_virtual_transactions_destination_account_id'), table_name='virtual_transactions')
    op.drop_table('virtual_transactions')
    # ### end Alembic commands ###

