"""add_finance_tables

Revision ID: e3d851ea9d54
Revises: 3de79b987bc8
Create Date: 2026-06-19 13:55:57.190316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d851ea9d54'
down_revision: Union[str, Sequence[str], None] = '3de79b987bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balance_paise', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_accounts_account_number'), 'virtual_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_virtual_accounts_owner_id'), 'virtual_accounts', ['owner_id'], unique=False)
    op.create_table('money_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_account_id', sa.UUID(), nullable=True),
    sa.Column('to_account_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['virtual_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_account_id'], ['virtual_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_requests_from_account_id'), 'money_requests', ['from_account_id'], unique=False)
    op.create_index('ix_money_requests_requester', 'money_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_money_requests_requester_id'), 'money_requests', ['requester_id'], unique=False)
    op.create_index('ix_money_requests_status', 'money_requests', ['status'], unique=False)
    op.create_index(op.f('ix_money_requests_to_account_id'), 'money_requests', ['to_account_id'], unique=False)
    op.create_table('virtual_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('holder_id', sa.UUID(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_month', sa.Integer(), nullable=False),
    sa.Column('expires_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_cards_account_id'), 'virtual_cards', ['account_id'], unique=False)
    op.create_index(op.f('ix_virtual_cards_holder_id'), 'virtual_cards', ['holder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_cards_holder_id'), table_name='virtual_cards')
    op.drop_index(op.f('ix_virtual_cards_account_id'), table_name='virtual_cards')
    op.drop_table('virtual_cards')
    op.drop_index(op.f('ix_money_requests_to_account_id'), table_name='money_requests')
    op.drop_index('ix_money_requests_status', table_name='money_requests')
    op.drop_index(op.f('ix_money_requests_requester_id'), table_name='money_requests')
    op.drop_index('ix_money_requests_requester', table_name='money_requests')
    op.drop_index(op.f('ix_money_requests_from_account_id'), table_name='money_requests')
    op.drop_table('money_requests')
    op.drop_index(op.f('ix_virtual_accounts_owner_id'), table_name='virtual_accounts')
    op.drop_index(op.f('ix_virtual_accounts_account_number'), table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    # ### end Alembic commands ###

